addons:
  apt:
    packages:
    - gforth

language: node_js
node_js:
  - "node"

before_install:
  - npm install -g grunt-cli

install:
  - apt-get install -y gforth

script: gforth test/test.fth | grep Test-OK

